torchrun \
    --standalone \
    --nproc_per_node=1 \
    --master_port=29500 \
    train_ddp_one_model.py \
    --lora \
    --lora_r 16 \
    --lora_alpha 64 \
    --model_name Qwen/Qwen3-VL-Embedding-2B \
    --model_backbone qwen3_vl \
    --bf16 \
    --pooling eos \
    --normalize True \
    --temperature 0.02 \
    --dataset_name TIGER-Lab/MMEB-train \
    --subset_name OK-VQA A-OKVQA DocVQA InfographicsVQA ChartQA Visual7W \
    --dataset_split original \
    --image_dir "/home/gdi-user/enguyen/research_vllm/test/VLM_Embed/vlm2vec_train/MMEB-train" \
    --output_dir ./training/AdaptiveMRL_Qwen3_stage1 \
    --per_device_train_batch_size 16 \
    --gradient_accumulation_steps 1 \
    --learning_rate 1e-5 \
    --num_train_epochs 1 \
    --save_total_limit 2 \
    --logging_steps 1 \
    --save_strategy epoch \
    --seed 42 \
    --weight_decay 0.01 \
    --warmup_ratio 0.03 \
    --lr_scheduler_type constant \
    --optimizer_name adamw \
    --image_resolution mid \
    --kd_loss_type adaptive_mrl_stage1 \
    --nested_dims 64 128 256 512 1024 2048 \
    --stage1_phase all \
    --stage1_projection_spec "2048->1024,1024->512,512->256,256->128,128->64" \
    --align_l1_weight 1.0 \
    --full_dim_l1_weight 0.0 \
    --align_l1_weights "64:0.6,128:0.6,256:0.6,512:0.6,1024:0.6" \
    --orthogonal_weight 0.01 \
    --adaptive_cycle_weight 0.05 \
    
